[package]
name = "shadow_api"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1"
serde_path_to_error = "0.1"

lol_html = "0.3.1"
